### ISSUE TITLE
Add test coverage for Colosseo 0014-NP-VAMM-004

### ISSUE THREAD

**Issue by witgaw** [vegaprotocol/core-test-coverage#1328]
Add test coverage for Palazzo [0014-NP-VAMM-004](https://github.com/vegaprotocol/specs/blob/colosseo/protocol/0090-VAMM-automated_market_maker.md#0014-NP-VAMM-004)

**Comment by Sohill-Patel** [comment]
duplicate of https://github.com/vegaprotocol/core-test-coverage/issues/1377
